### PR TITLE
Update Maven, fix bugs with databases

### PR DESCRIPTION
**Pull request by Di3mex**
Updated pom.xml for 1.6.2 and added IntelliJ specific folders to gitignore.

Database settings have been separated into nodes for host, port, type and name. The resulting jdbc string is build in the code. This makes it easier for people that don't know how to format a jdbc string correctly to migrate to databases. Errors while connecting to a database are now printed to console instead of being silently ignored.

Admin claims didn't transfair to the database correctly because there are areas in the code where the owner of a claim is accessed via the field instead of using the getter method. The getter method sets the field of the Claim if it's an adminclaim. Additionally the default admin name was retrieved from a DataStore before the datastore was initialized.

A few NPE's are caught correctly now and will print a human readable error to the console.

Notes:
I encountered countless unused variables and code that has been commented out while looking through the code. I assumed that most variables are kept as a reminder so I didn't remove them.

Also the database design is far from optimal and basically just the flatfile storage copied to database fields. This should be fixed before the full release.

### CODE REVIEW

**Comment by Di3mex** [comment]
What's the issue here, why aren't you pulling this and not even leaving a comment?

**Comment by Tux2** [comment]
I'm sorry about that, I just haven't had time, I've been working on the enjin plugin. BC_Programming, although he assists, he doesn't pull any pull requests. I'll take a look over this, but it cannot be automatically merged.

**Comment by BCProgramming** [comment]
I didn't comment because I always get called a big meanie poopy-face.

**Comment by Di3mex** [comment]
I can update it so it can be merged, just tell me if you want the separated nodes for databases.

**Comment by riddle** [comment]
Why cannot this be merged, if it works and doesn’t break anything?

Also, BCProgramming, please, open up tickets on this GitHub page. Use it for 7.8-beta related bugs only, dev.bukkit.org is so bad at organization and important bugs which prevent the beta from working properly are being ignored.

**Comment by BCProgramming** [comment]
> Why cannot this be merged, if it works and doesn’t break anything?

Because it destroys the refactored dataStore config separation that has been added since.

It also makes changes to pom.xml, which isn't even supposed to be in the repo anymore, maven support has been completely removed because the people who want it are needy and complain all the time about things that don't matter. 

> Also, BCProgramming, please, open up tickets on this GitHub page. 
> Use it for 7.8-beta related bugs only, dev.bukkit.org is so bad at organization 
> and important bugs which prevent the beta from working properly are being ignored.

If you think they are being ignored now, how would using github fix it? Not to mention if you are referring to the ones you posted, they were posted less than two days ago.

**Comment by Di3mex** [comment]
I would update the PR but I'm lying in bed with a flu. This was just supposed to be a starter PR to see if commiting more fixes is worthwhile. But it seems like this is not the case and you guys want to be left alone and have noone else bother you and tell you what to do.

First no reaction and then it's too late and can't be merged anymore.

> It also makes changes to pom.xml, which isn't even supposed to be in the repo anymore, maven support has been > completely removed because the people who want it are needy and complain all the time about things that 
> don't matter.

When your diaper is full and your bum is on fire there will be noone to help you out. You will have to clean it up yourself...

It saddens me to see in what state GP is, the golden days are over and it's time to move on.

Vale!

**Comment by riddle** [comment]
> If you think they are being ignored now, how would using github fix it? Not to mention if you are referring to the ones you posted, they were posted less than two days ago.

I mean just to have a back and forth discussion about 7.8 beta with people who will not post bugs related to some other plugin breaking something. There is a conscious group of developers or coders who can help, but you must allow that to happen. Not to mention a lot of stuff hasn’t even been documented. I would like to help, that’s all. I rely on GP daily and I’m not the only one who has to use 7.8 beta to support 1.6.2’s changes.

As for my problems, I don’t care that much. I just want to see this beta to move in a stable direction. The pace is scaring me, so many things still don’t work or are utterly confusing.

**Comment by BCProgramming** [comment]
> This was just supposed to be a starter PR to see if commiting more fixes is worthwhile.

From what it looks like you ran a few IntelliJ wizards and made a one-line change. PRs should not be filed against code style changes. They should either add substantial features (for example, the changing of the config nodes for database stuff would have been awesome if you didn't have the ill-fortune of posting this PR as I was refactoring my WC to abstract the different DataStore implementations, which required of course the config to not have anything dataStore-specific, meaning that the db config got moved to another configuration file. I believe it supports the same nodes you've mentioned in this PR, iirc, but there is no way to tag a PR as being merged without actually performing a merge of some description, or if there is I don't know how to do it. Aside from my WC being significantly changed, the PR didn't really have anything that I considered substantial; the effort to push my current WC and merge this request would have been longer than the time it took to add the two minor bugfixes it actually addresses.

> First no reaction and then it's too late and can't be merged anymore.

No, I saw them. However by that time my working copy was already way beyond the version for which the PR was made- in fact I believe at the time the original notification landed in my inbox I was already performing the split to separate the jdbc string since I was creating a new dataconfig.yml for it anyway. The only reason I actually ended up removing that feature and reverting it mostly back to the jdbc string was because of this PR. (not out of spite but rather because I wouldn't want somebody to think I saw this PR and them just implemented the change myself).

> > When your diaper is full and your bum is on fire there will be noone to help you out. You will have to clean it up 
> > yourself...

Well, first, I do this stuff professionally so I'm not afraid of SQL, Programming, or Design, and redesigning applications is something I do both in my spare time and for a living, and have already done for GP (eg. the Rules framework). So I'm not really sure what would need to be "cleaned up". I mean, I could run the same IntelliJ wizards you ran.

Re the database, however, I didn't design this DB schema but I've been making architectural changes that will allow any schema change that comes up in the future to require far less work, since at this point it cannot be "fixed" without a time-intensive migration code logic, which is part of why I've abstracted the actual dataStore somewhat. idea being that a re-considered database schema created from scratch would be implemented in a fresh dataStore subclass, implementing all the appropriate abstract methods, and the generic migration logic that migrates from any one datastore to any other datastore could then be used in some fashion to migrate existing MySQL database to the new form. In addition this framework would allow for the creation of dataStore implementations that support other database types, such as PostGres, which was integrated into the mySQL implementation as a result of another PR, but should ideally be a separate dataStore. (I'd say MSSQL could be another but let's be honest nobody is going to be using that with GP...). It would also allow add-on plugins to add their own dataStore's, so plugins could add support for other data formats such as XML if they so desired. Primarily it's added for the migration capability which would be useful since it would allow migration in any direction, in addition to more importantly allowing migration from any current dataStore to any dataStore added in the future- meaning a future dataStore that adds support for say sqllite, could be migrated to and from any other dataStore with ease, in addition to say "newMySQL" which would have some redesigned schema  that most likely ends up not really making things any better. (though it's certainly worth exploring). Being able to read from existing MySQL databases for GriefPrevention is far more important than the Schema being considered sub-optimal for secret reasons that aren't being shared.

That said, I'm not entirely convinced the current layout is far from optimal. Since it's used simply for data storage. I would 100% agree if determining if a claim existed at a given location or retrieving that claim resulted in a database hit, because then the Schema could be optimized for lookups based on location. however, this is not the case and all claim accesses are optimized using a Chunk-based HashMap lookup that Tux added to replace the sequential lookup that somehow didn't flip any "this is a stupid way to do it" alarms in somebody's head. The only real changes I can see would be abstracting the Accessor/Manager/Builders/etc database fields to a separate database and using a foreign key lookup, but I'm not really sure how that would really make things much more efficient- even if that foreign table was indexed by the lookup field, I'm not convinced it would be faster in the long-run than simply using Split() on the field after it has been retrieved, particularly since I don't think you could easily use a single query to map multiple foreign record fields into a single ResultSet record, meaning the loading would take multiple queries. It has been changed to use SQL Update rather than a Delete and an INSERT to change database records, which has helped make the DB dataStore a little less stupidly slow.

> It saddens me to see in what state GP is, the golden days are over and it's time to move on.

Yes, the golden days where the maintainer would say that a suggested feature should be in a separate add-on and use an afterthought API that only exposed half of what was needed and didn't have any events. World-based configuration was 'impossible'. and adding support for MCPC+ worlds was considered impossible. The good old days, huh?

> > I mean just to have a back and forth discussion about 7.8 beta with people who will not post bugs related to
> > some other plugin breaking something. There is a conscious group of developers or coders who can help, but 
> > you must allow that to happen. Not to mention a lot of stuff hasn’t even been documented. I would like to help, 
> > that’s all. I rely on GP daily and I’m not the only one who has to use 7.8 beta to support 1.6.2’s changes.

If a bug in another plugin is a result of an API change, that should be filed against GP. 

My only issue is that my general interaction with Pull Requests has been overwhelmingly negative. Since I have no reason to expect such a discussion section to be anything more than a bunch of people telling me what an asshole I am, I'm not really sure there would be much point, except to maybe make me clock more hours on actual work instead (which, come to think of it, would work out OK too). I mean, I can basically choose to spend my time working in Java on GriefPrevention and getting paid nothing but people telling me off, or I can get paid well to work on applications I helped build with a group of nice co-developers with whom I have mutual professional respect.

Even so, I'll see if I can open up such a section anyway. I cannot guarantee I will respond very often though. I might need to get Tux to open it. If for no other reason than discussion amongst those folks you speak of. For example, they can debate on exactly how much of an asshole I am for not responding very often, which is pretty much what happens with PRs too.

**Comment by riddle** [comment]
I think your post in /r/admincraft showed that there is a group of people who can think critically and get into developer’s mindset, not just throw feature requests at them or bitch about DB choice.

For example for me personally, I’m more interested in filing issues about consistency and configuration not being confusing without a huge text wall opened next to it. RebalanceVillagers’ config comes to mind. Everything I need to know, around yaml nodes which I want to change.

**Comment by BCProgramming** [comment]
Fair enough :) I ping'd Tux because I'm not able to open Discussion or Tickets section on the Repo, so hopefully he'll get around to that.

The /r/AdminCraft discussion was very fruitful I think, if that's the sort of think you are imagining I can see it being very useful.

If you are referring to comments in the yaml: I don't think there is a way to do that in GP as it is. I'm not even sure if it's possible, not without introducing more problems. I did explore this but wasn't able to find a way to programmatically add comments.

**Comment by Di3mex** [comment]
@BCProgramming 
I'm manually redoing the changes and leaving all the refactoring out, sorry I included it in the first place. Even though the 2 bugfixes where more or less one-liners you have to keep in mind that those small things can take a long to time to find. Have you fixed them in the meantime? I'm not sure.

Regarding maven: I'll update the pom.xml and include it aswell. Even though you don't like maven keep in mind you are making it easier for others to work together with you if they can painlessly pull all the required dependencies. 

Regarding comments in yaml: Most developers with simple configs just include the comments in a prewritten file and copy it over. As long as you don't write back to the file, for example to correct false input the comments are preserved. 

Using the default bukkit yml implementation will not allow for the use of comments. You have to either write the whole node tree with comments yourself or add them to the file after bukkit wrote the node tree. 

I planned on writing a class that will take a node-comment table/map as input and add those comments to a given file. The implementation would be completely independent from the way you access your config. You would just provide a file and the table which maybe could even be a txt-file in your plugin.jar or something.

Also comments should be able to be turned of once you know what the nodes do as comments can bloat a configfile and make it hard to actually find a node you want to change without ctrl+f.

Concerning configs: In extrahardmode I use a enum based config which I believe is robust, makes it easy to understand the layout of a config, add new nodes and use predefined input validation.
[An example of usage](https://github.com/Di3mex/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/features/MoreTnt.java#L53). [The base config](https://github.com/Di3mex/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/service/config/MultiWorldConfig.java), [Config specific to ehm](https://github.com/Di3mex/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/config/RootConfig.java), [Enum with all nodes](https://github.com/Di3mex/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/config/RootNode.java). 

The special things about my configuration:
- You have one main config  in which you specify your worlds or use '@all' if you want this config to be for all worlds. 
- Then and only if you need to change something in a specific world the user can copy the main config file and rename it to whatever he likes. 
- He will then change the worlds in the header of the file, can be multiple world or just one and change the settings he wants to override in the world.
- All nodes that are the same in the main config will change to the keyword 'inherit' which makes it possible to see what has been overriden and what still has the default value.

Let me know if you like it or not, then I can maybe implement it, will be lots of tedious copy and pasting, but I'll do it.

As to the db schema: I can write down what I would change, but I'm not a professional in any way :D.

Regards, Diemex

**Comment by Di3mex** [comment]
Went through the code most things seem to be fixed already, which is good. Only remaining part was the one NPE when no datastore is present and the updated pom.xml.

When I history rewrite the repo github doesn't seem to like that and I actually have to open a new PR.

**Comment by BCProgramming** [comment]
> I'm manually redoing the changes and leaving all the refactoring out, sorry I included it in the first place. Even 
> though the 2 bugfixes where more or less one-liners you have to keep in mind that those small things can take 
> a long to time to find. Have you fixed them in the meantime? I'm not sure.

True. I think I stumbled on them. It's also possible that I changed some of them after seeing them in this commit (again, simply because it was faster to make such a quick change that way than to merge the pull and then try to resolve the conflicts between the repo and my working copy).

> Regarding maven: I'll update the pom.xml and include it aswell. Even though you don't like maven keep in mind 
> you are making it easier for others to work together with you if they can painlessly pull all the required 
> dependencies.

Yeah I was more or less saying that it was removed from my working copy and that is why it would probably need updated. I've merged the other pull request, FWIW, though I'll still have a few conflicts to resolve locally, there are probably far fewer now. (and most of the changes I've made since my last push are not in the files changed).

> Regarding comments in yaml: Most developers with simple configs just include the comments in a prewritten 
> file and copy it over. As long as you don't write back to the file, for example to correct false input the comments 
> are preserved.

Yeah that's the problem though. The idea is that this way new cfg nodes can be added to a file that already exists. so that new rules or whatever could be added, and they would appear in existing configurations with default values. No real way to do it otherwise and still get that, AFAIK.

> Using the default bukkit yml implementation will not allow for the use of comments. You have to either write the >whole node tree with comments yourself or add them to the file after bukkit wrote the node tree.

Right now it is using the YamlConfiguration class. Ideally each node should take an optional comment and just tack it on after, at the very least. Doesn't look like it does though.

Concerning configs: In extrahardmode I use a enum based config which I believe is robust, makes it easy to understand the layout of a config, add new nodes and use predefined input validation.
An example of usage. The base config, Config specific to ehm, Enum with all nodes.

> I think Riddle was talking more about being able to read the actual .yml config file, though. All access to the larger Configuration file (WorldConfigs) is abstracted to a separate class already- it reads the data in each time a world loads.
> 
> You have one main config in which you specify your worlds or use '@all' if you want this config to be for all 
> worlds.Then and only if you need to change something in a specific world the user can copy the main config file 
> and rename it to whatever he likes.

Thing is, this is sorta what I want to avoid. Sometimes a plugin can create temporary worlds for various purposes, and when dealing with things like MCPC+, that functionality can get pretty crazy. Obviously asking admins to create a special configuration for every mystcraft world would be pretty silly. GP's world Configurations are loaded per-world by looking for <worldname.cfg> and if it's not found it copies a template file. the template could be set and made by default have comments, but since the plugin than loads the config right away those comments would be stripped off because it rewrites the config to add missing nodes.

> All nodes that are the same in the main config will change to the keyword 'inherit' which makes it possible to 
> see what has been overriden and what still has the default value.

This could probably be added to GP. But again, I think riddle's main issue is that GP's world configurations are confusing. Ideally they would have comments around appropriate parts. IMO a lot of it is sort of self-describing because of it's name, the only tricky part is understanding the rules and what each rule does, (as far as I'm concerned). but comments would still be useful, if only to describe each rule inline with a sentence or two.

> As to the db schema: I can write down what I would change, but I'm not a professional in any way :D.

I had a few ideas myself but haven't gotten to a point where I could try to make a "newMySQL" database store.

**Pull request closed without merging**
