### PR TITLE
Another plugin should be able to prevent the creation of claims.

### PR DESCRIPTION
**Pull request by Slind14**

### CODE REVIEW

**Comment by BCProgramming** [comment]
GP-Aware plugins can do so by handling the BeforeClaimCreated Event and cancelling that event. It will also work for cancelling any sort of claim creation.

**Comment by Slind14** [comment]
A public plugin should not use the highest priority.

**Comment by BCProgramming** [comment]
That's probably why it was set to the lowest priority.

**Comment by Slind14** [comment]
lowest is the highest priority in bukkit :/

**Comment by BCProgramming** [comment]
Oh. That's pretty dumb. It looks like the enumeration really should be called "EventImportance" instead of EventPriority, since it is exactly the opposite of what priority means usually.

I tried to determine where it was changed but it has been in the plugin this way since Ryan's initial commit, so I don't know if it was added to address some other problem.

**Comment by Slind14** [comment]
Maybe he didn´t know that, too. A small question why is there stained glass but bukkit 1.6.4 as depencie ?

**Comment by BCProgramming** [comment]
dependency where? I don't touch pom.xml, ever.

**Comment by Slind14** [comment]
ohh ok. I had to delete it because I´m still on 1.6.4

**Comment by BCProgramming** [comment]
You can reference the 1.7.2 API, and still run it on a 1.6.4 server, fwiw.

**Comment by Slind14** [comment]
you are right, thanks

**Pull request merged**
