### PR TITLE
Big fixes for YamlDataStore

### PR DESCRIPTION
**Pull request by Alshain01**
Just a couple of things I missed.

### CODE REVIEW

**Comment by BCProgramming** [comment]
Oh, it looks like YamlDataStore is breaking the Jenkins build, because it uses Java 7 features and Jenkins is building for Java 6:

src/me/ryanhamshire/GriefPrevention/YamlDataStore.java:183: error: diamond operator is not supported in -source 1.6
        List<PlayerData> pData = new ArrayList<>();

**Comment by Alshain01** [comment]
BC, I just saw this comment, I take it you got this fixed since the conversation in the other PR.  I thought you were using 7 because there was another class (ThreadedDataStore?) that had Java 7 stuff.

**Comment by BCProgramming** [comment]
Yeah I made the necessary changes. The only reason it was using Java 7 before was simply because I didn't have a Java 6 SDK installed and didn't know about the javac arguments to change the source level. I don't think ThreadedDataStore used Java 7 features; it's unfinished and wasn't supposed to be committed anyway since it's far from finished.

**Comment by Alshain01** [comment]
I think ConcurrentLinkedDeque was throwing the compile error, I believe that is Java 7 only. I do wish Mojang would update though.  If you use something like essentials and MCStats to make a judgement, only 3% of servers are running Java 6 or earlier, time to let it die.

**Comment by BCProgramming** [comment]
Yeah that would make sense. the Source flag only changes the language version, but still compiles against the Java 7 JDK. Thankfully, ThreadedDataStore isn't used anywhere so it should be fine.

**Comment by Alshain01** [comment]
In IntelliJ, the language level is in the Project Structure options.  The Source flag only works if you compile with Maven, not IntelliJ (View -> Tool Windows -> Maven). Even then, the compiler will still throw errors based on the Project Structure.

**Pull request merged**
