### PR TITLE
Prevent NoSuchFieldError for pre-1.6.x on Material.LEASH

### PR DESCRIPTION
**Pull request by descention**

### CODE REVIEW

**Comment by BCProgramming** [comment]
I Don't think Enum fields should be changed to magic numbers. This was already done for Item Frames in a few places and it looks horrible. Can we not catch the exception or perhaps have a function that can use missing classes/fields to determine the minecraft version? (eg. isVersion164()) Similar to what was done for Horses?

**Comment by descention** [comment]
Yeah, that would be the better idea. I'll make changes to this later this week.

**Comment by BCProgramming** [comment]
I ended up adding a few simple functions that can determine if the minecraft version is a desired version or later.

Right now it goes back to 1.2.5, since I believe the API changed and GP won't load on earlier versions at all.

It just checks for certain fields in the Material Enum, based on materials added to each version. STAINED_GLASS for 1.7, STAINED_CLAY for 1.6, REDSTONE_BLOCK for 1.5, ENCHANTED_BOOK for 1.4, COMMAND (command block) for 1.3, and REDSTONE_LAMP_ON for 1.2. That's as far as I'm willing to support and I'm not sure how compatible we could make it with earlier versions (not to mention right now 1.4.7 and later would be like 99.9% of people who want to use the plugin).

EDIT: of course, this function call was inserted where the LEASH material is checked. I also reverted the check beneath it that used a hard-coded ID for the name tag back to Material.NAME_TAG and stuck in the version check so it would get skipped as well.

**Comment by descention** [comment]
Cool. Your code is much nicer than what I was trying to do. I'll just close this pull request.

**Pull request closed without merging**
