### PR TITLE
Server shutdown takes incredibly long time, trying to find causes

### PR DESCRIPTION
**Pull request by riddle**
GriefPrevention 7.8, this build: http://build.yu8.me:8080/job/GriefPrevention/147/

Related: https://github.com/Tux2/GriefPrevention/commit/310e93352beba34c89bc35fdcda3f1867d8b19d1#L2R380

Upon server stop there is a very long slowdown, and a stream of logs http://i.imgur.com/hkXZhUk.jpg It’s not even the slowdown, it’s read timeout on the server and players never seeing a normal server closed screen (with message defined in `bukkit.yml`).

What we include is a series of tests (ignore my failed Maven commits, focus on Matej’s) which caused us to notice that despite having ~4200 claims in DB, it’s not DB timing that causes the server to freeze on stop and throw read timeouts.

I’m opening this for a discussion, devs to devs.

### CODE REVIEW

**Comment by riddle** [comment]
OK, here is the fix by @matejdro.

https://github.com/MCNSA/GriefPrevention/commit/89b6e6304bb037b123de933f06fea25007258e6f

Shutdown is snappy again, no timeouts, the whole thing takes 1s. Please think of adding manually to beta (we realize this pull request is junky), it’s a no brainer.

**Comment by riddle** [comment]
Can you incorporate the 89b6e6304bb037b123de933f06fea25007258e6f commit into the codebase and close this pull request please?

**Comment by BCProgramming** [comment]
"Deleting all the claims at once" is a bit of a hack workaround. Sure, it speeds up deleting every claim, but the thing is, GP shouldn't have been deleting any claims anyway. records should have been updated. This was changed in a dev build to use UPDATE instead of a DELETE and INSERT when the claim record already exists. Debug output both from migration as well as server shutdown is faster; I suspect using Transactions during plugin shutdown could speed it up even more.

**Comment by riddle** [comment]
Oh, so a newer build has it fixed? Swell!

Also, sorry to use this channel but do you think it could be possible for you to open GitHub Issues (or maybe a better hidden repo so it’s not swarmed by non-technical people)? I’ve been running 7.8’s beta on a production server and I think I might have some interesting cases with permissions where they don’t work just right. I’m not sure where to submit them now (dev.bukkit.org’s page is just a stream of noise).

**Comment by BCProgramming** [comment]
I don't know if it 100% fixes the issue, I do know that it seems a lot faster watching the debug output, before iirc it took something like 3 seconds between each claim saying it was saved, once I changed it to use UPDATE instead of a DELETE and INSERT into the database it is noticably faster.

re: Permissions, I was actually thinking of reworking them for more granularity, if only so I can actually properly document everywhere they are checked. (I'm speaking of server permissions nodes and not the claim permissions)

You could create a tickets on the bukkitdev page. There are many open tickets, because I don't like closing tickets without some feedback from the author, but I always see new ones that are filed. Thanks :)

**Pull request closed without merging**
