### PR TITLE
Fix subdivisions not getting an id

### PR DESCRIPTION
**Pull request by ghost**
Subdivisions are not given a claim id in the datastore.

It looks like it is returning before the incrementNextClaimID section and never given a claim id. By moving the lines where that is further up in the addClaim and saveClaim functions it should fix the issue.

However it won't fix all those subdivisions created with the issue, at least one other check has to be added for that where it sends the subdivision back.

Close but no cigar, as they say =)

### CODE REVIEW

**Comment by Tux2** [comment]
You forgot to save the claim back to disk when getting subclaims without IDs and adding the ID. Add that and I'll pull it in.

**Comment by ghost** [comment]
Hey, I'm not sure if you still want to add this or not but I believe I did what you wanted =)

**Comment by Tux2** [comment]
Unfortunately there's other things in the file format that we have to change in order to get subdivision's claim IDs to stick across reboots, as well as the new code you were doing would actually save the claim as a parent claim so this is only a partial solution. I'm sorry, I totally forgot about that.

**Comment by ghost** [comment]
Ah ok, well I am sure you will get it in tip top shape. Thanks =)

**Pull request closed without merging**
