### PR TITLE
Large Restructure - Please make sure you are happy before accepting pull

### PR DESCRIPTION
**Pull request by smc87**
1. Convert to maven project
2. Build local Repository instead of referencing external jars
3. Rework dispenser logic for water / lava / buckets. Now protected from dispensing into/outof claims you do not own. Rework of vector logic to use getFacing()
4. Specfify UTF-8 encoding - Build is no longer platform specfic - hopefully fixes negative claiming issue - (speculative)
5. Update MC version dependency

### CODE REVIEW

**Comment by smc87** [comment]
Give me a shout if you have any questions

**Comment by riddle** [comment]
> Convert to maven project

Good luck. GP maintainers have 0 interest in Maven and expressed serious distaste for how it impedes their _workflow_.

> Build local Repository instead of referencing external jars

This is not advised by Maven and you should avoid adding jars to your repository if you can help it.

**Comment by BCProgramming** [comment]
"Please make sure you are happy before accepting pull"

Does this mean you aren't sure if it works?

Normally I wouldn't really consider any switch to Maven for the reasons above- primarily that it makes it a pain in the butt for me to make changes, also it was using Maven for a few builds but I don't know if that even worked. I couldn't figure out how to update it to Bukkit 1.5 at the time (or possibly 1.6) so I basically reverted that change to get it to work. I think it was using a local repository as well, which may explain the difficulties I was having- it simply refused to build with the new jar, I forget the details.

If it builds and doesn't cause any obvious problems, we can give it a shot.

**Comment by smc87** [comment]
Hi, sorry for the confusion in the build request title, it does definitely work, i just wasnt sure if (like you said) you would be happy with maven...i saw another maven request thats sat there for awhile so wasnt sure.

Also the repositories things just makes the code more portable in my opinion, if you want to work on it you don't need anything more than the code that is on github. 

If you like you can try the latest build from here thats running on my server at the minute:
https://smc87.ci.cloudbees.com/job/GPFork/

**Pull request merged**
